## Default Turrets Configuration

# activeOnCreate: True means new turrets will be active by default.
# allowAllToMan: True allows all players (with permissions) to man anyone's turrets.
# allowAllToChangeAmmo: True allows all players (with permissions) to change the ammo type of anyone's turrets.
# allowAllToAddAmmoBox: True allows all players (with permissions) to add/remove ammo boxes from anyone's turrets.
# allowAllToDestroy: True allows all players (with permissions) to destroy anyone's turrets.
# allowAllToModActivate: True allows all players (with permissions) to activate/deactivate anyone's turrets.
# pickupUnlimArrows: True allows players to pick up arrows shot by turrets with unlimited ammo.
# pickupAmmoArrows: True allows players to pick up arrows shot by turrets using ammo boxes.
activeOnCreate: true
allowAllToMan: false
allowAllToChangeAmmo: false
allowAllToAddAmmoBox: false
allowAllToDestroy: false
allowAllToModActivate: false
pickupUnlimArrows: false
pickupAmmoArrows: true
defaultPvpOn: false
defaultUseBlacklist: true
defaultUseAmmoBox: true

# Box Ammo types: List of all ammo types used by turrets from ammo boxes, separated by commas
# Items listed first will be used first if possible, second second, etc.
# Supported types are: arrow,egg,snow_ball,potion,exp_bottle,monster_egg,fireball
boxAmmoTypes: arrow,snow_ball
unlimitedAmmoTypes: arrow,snow_ball

# Max turrets per player: Sets the maximum number of turrets a player can have. The permission turrets.ignoremaxturrets can override this.
maxTurretsPerPlayer: 12

# Upgrade Tiers
#
# Names of tiers must be placeable blocks, except for "default" (chosen if the block under a turret's post matches none of the rest)
#
# firingInterval: Delay between shots (in ticks)
# range: Maximum distance for finding targets
# accuracy: Lower values are more accurate
tiers:
  default:
    firingInterval: 40
    range: 8.0
    accuracy: 3.0
  iron_block:
    firingInterval: 20
    range: 10.0
    accuracy: 2.0
  gold_block:
    firingInterval: 10
    range: 12.0
    accuracy: 1.0
  diamond_block:
    firingInterval: 5
    range: 15.0
    accuracy: 0.5