# General Plugin Information
name: Turrets
main: me.azazad.turrets.TurretsPlugin
version: 0.1.1
author: azazad
database: false
depend: [Vault]

# Commands
commands:
   turrets:
      aliases: [tur]
      description: Turrets administrative command.
      usage: /<command>
      permission: turrets.command.turrets
      permission-message: Permission <permission> required
      
# Permissions
#permissions:
#  turrets.*:
#    description: Gives access to all Turrets permissions.
#    children:
#      turrets.reload: true
#      turrets.addturret: true
#      turrets.manturret: true
#    turrets.reload:
#      description: Allows user to reload the Turrets plugin. Often necessary for all turrets to load.
#      default: op
#    turrets.addturret:
#      description: Allows user to create a new turret.
#      default: true
#    turrets.manturret:
#      description: Allows user to man a turret.
#      default: true